# These are supported funding model platforms
community_bridge: #purvesh77
github: [Purvesh77]
issuehunt: #
ko_fi: #USERNAME
open_collective: #USERNAME
otechie: #USERNAME
patreon: #USERNAME
tidelift: #PLATFORM-NAME/PACKAGE-NAME
custom: https://github.com/Purvesh77